### ISSUE TITLE
six library is missing

### ISSUE THREAD

**Issue by biomaks** [yashaka/selene#135]
Tried basic example from    README.md file.

    Traceback (most recent call last):
      File "login_test.py", line 1, in <module>
        from selene.api import *
      File "/Users/erik/.virtualenvs/ui-tests/lib/python3.6/site-packages/selene/api/__init__.py", line 1, in <module>
        from selene import config, browser, browsers
      File "/Users/erik/.virtualenvs/ui-tests/lib/python3.6/site-packages/selene/browser.py", line 6, in <module>
        import selene.driver
      File "/Users/erik/.virtualenvs/ui-tests/lib/python3.6/site-packages/selene/driver.py", line 11, in <module>
        from selene.elements import SeleneElement, SeleneCollection
      File "/Users/erik/.virtualenvs/ui-tests/lib/python3.6/site-packages/selene/elements.py", line 23, in <module>
        from selene.wait import wait_for
      File "/Users/erik/.virtualenvs/ui-tests/lib/python3.6/site-packages/selene/wait.py", line 1, in <module>
        import six
    ModuleNotFoundError: No module named 'six'

**Comment by SergeyPirogov** [comment]
Which command did you use to install selene?

**Comment by biomaks** [comment]
`pip install selene --pre`

`pip freeze` output:

    backports.functools-lru-cache==1.4
    certifi==2017.4.17
    chardet==3.0.4
    colorama==0.3.9
    configparser==3.5.0
    crayons==0.1.2
    future==0.16.0
    idna==2.5
    requests==2.18.1
    selene==1.0.0a11
    selenium==2.53.1
    urllib3==1.21.1
    webdriver-manager==1.4.5

**Comment by SergeyPirogov** [comment]
Python version?

**Comment by biomaks** [comment]
python3.6

**Comment by SergeyPirogov** [comment]
Need to investigate, because we tested it with python <= 3.5

**Comment by SergeyPirogov** [comment]
Can confirm, that six is missed. Need to fix it. Temporary solution is to install it using **pip install six**

**Comment by SergeyPirogov** [comment]
fixed by https://github.com/yashaka/selene/pull/136
