### ISSUE TITLE
should(be.empty) fails

### ISSUE THREAD

**Issue by mrts** [yashaka/selene#185]
`should(be.empty)` fails with `AttributeError: ("'find_element_by_id' object has no attribute 'get_actual_webelements'",)`.

Indeed, when examining the Selenium WebElement in `CollectionCondition.fn()` then it has a method called singular `get_actual_webelement()` instead of plural `get_actual_webelements()` :

```pdb
> [...]\venv\lib\site-packages\selene\conditions.py(301)fn()
-> return self.match(elements.get_actual_webelements())
(Pdb) elements
<selenium.webdriver.remote.webelement.WebElement (session="e739a6ec35ccb28aa05210ad9a0b43b4", element="0.19582947914802085-2")>
(Pdb) elements.get_actual_webelements
*** AttributeError: 'find_elements_by_class_name' object has no attribute 'get_actual_webelements'
(Pdb) dir(elements)
['__abstractmethods__', '__call__', '__class__', '__delattr__', '__delegate__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_actions_chains', '_execute_on_webelement', '_locator', '_webdriver', 'all', 'assure', 'assure_not', 'by', 'by_css', 'by_css_or_by', 'cached', 'caching', 'clear', 'click', 'context_click', 'double_click', 'element', 'elements', 'find', 'find_all', 'find_element', 'find_element_by_class_name', 'find_element_by_css_selector', 'find_element_by_id', 'find_element_by_link_text', 'find_element_by_name', 'find_element_by_partial_link_text', 'find_element_by_tag_name', 'find_element_by_xpath', 'find_elements', 'find_elements_by_class_name', 'find_elements_by_css_selector', 'find_elements_by_id', 'find_elements_by_link_text', 'find_elements_by_name', 'find_elements_by_partial_link_text', 'find_elements_by_tag_name', 'find_elements_by_xpath', 'first_child', 'following_sibling', 'get_actual_webelement', 'get_attribute', 'hover', 'id', 'is_displayed', 'is_enabled', 'is_selected', 'location', 'location_once_scrolled_into_view', 'parent', 'parent_element', 'press_down', 'press_enter', 'press_escape', 'press_tab', 'rect', 's', 'screenshot', 'screenshot_as_base64',
'screenshot_as_png', 'scroll_to', 'send_keys', 'set', 'set_value', 'should', 'should_be', 'should_have', 'should_not', 'should_not_be', 'should_not_have', 'size', 'ss', 'submit', 'tag_name', 'text', 'value_of_css_property']
(Pdb) elements.get_actual_webelement()
<selenium.webdriver.remote.webelement.WebElement (session="e739a6ec35ccb28aa05210ad9a0b43b4", element="0.19582947914802085-2")>
```

## Setup

```bash
$ pip install 'selene>=1.0.0a13'
Collecting selene>=1.0.0a13
  Using cached https://files.pythonhosted.org/packages/30/c1/c8a7dcb36b9a89ab9ae5a9a422e6fd66a3d3412f49d84bc0477637e30453/selene-1.0.0a13-py2.py3-none-any.whl
Collecting selenium (from selene>=1.0.0a13)
  Using cached https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl
```

So pip by default pulls in latest Selenium (in this case *selenium-3.141.0*). Has this worked before and if yes, shouldn't selene pin the Selenium version? Or is this not related to Selenium version?

## Steps to reproduce

Create the following `test.py` and run it:

```py
from selene import config
from selene.browsers import BrowserName
from selene.api import *

config.browser_name = BrowserName.CHROME

browser.open_url('https://gmail.com')
s('#identifierId').should(be.empty)
```

This fails with

```
Traceback (most recent call last):
  File "\test-selene\venv\lib\site-packages\selene\wait.py", line 13, in wait_for
    return condition.fn(entity)
  File "\test-selene\venv\lib\site-packages\selene\conditions.py", line 300, in fn
    return self.match(elements.get_actual_webelements())
AttributeError: 'find_element_by_id' object has no attribute 'get_actual_webelements'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\test-selene\venv\lib\site-packages\selene\elements.py", line 188, in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
  File "\test-selene\venv\lib\site-packages\selene\wait.py", line 35, in wait_for
    reason=reason_string), screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
            failed while waiting 4 seconds
            to assert Size
            for first_by('css selector', '#identifierId')

            reason: AttributeError: ("'find_element_by_id' object has no attribute 'get_actual_webelements'",)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    s('#identifierId').should(be.empty)
  File "\test-selene\venv\lib\site-packages\selene\elements.py", line 306, in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
  File "\test-selene\venv\lib\site-packages\selene\elements.py", line 193, in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
selenium.common.exceptions.TimeoutException: Message:
            failed while waiting 4 seconds
            to assert Size
            for first_by('css selector', '#identifierId')

            reason: AttributeError: ("'find_element_by_id' object has no attribute 'get_actual_webelements'",)
```

**Comment by mrts** [comment]
Also tried with Selenium 2.53.1, same problem:

```bash
$ pip install selenium==2.53.1
$ python test.py
...
Traceback (most recent call last):
...
AttributeError: 'find_elements_by_tag_name' object has no attribute 'get_actual_webelements'
```

**Comment by ibalagurov** [comment]
@mrts Does it work if instead of using `s('#identifierId').should(be.empty)` use collection finder `ss('#identifierId').should(be.empty)` ?

**Comment by Maratori** [comment]
@mrts If you want to assert value is empty, then you should use `('#identifierId').should(be.blank)`

**Comment by mrts** [comment]
Thank you, now I understand - `be.empty` is for collections and `be.blank` is for single items. `s('#identifierId').should(be.blank)` works like a charm! This should be documented better, let's see if I can create a doc patch.
