### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by darviarush** [yashaka/selene#199]
При установке setup.py импортирует версию из selene/\_\_init\_\_.py, который в свою очередь  импортирует selene/core/entity.py и тот пытается проимпортировать ещё не установленный selenium.

```
Collecting git+https://github.com/yashaka/selene.git (from -r /root/requirements.txt (line 8))
  Cloning https://github.com/yashaka/selene.git to /tmp/pip-req-build-sclb12ny
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-sclb12ny/setup.py", line 2, in <module>
        from selene import __version__
      File "/tmp/pip-req-build-sclb12ny/selene/__init__.py", line 24, in <module>
        from selene.core.entity import Browser as _custom_browser, Config as _custom_config_for_custom_browser
      File "/tmp/pip-req-build-sclb12ny/selene/core/entity.py", line 30, in <module>
        from selenium.webdriver import ActionChains
    ModuleNotFoundError: No module named 'selenium'
```

**Comment by yashaka** [comment]
I am not sure that setup.py somehow should install a lib prerequisites first...

Before runnig setup.py you have to install prerequisites on your own by calling

```bash
pipenv install
```
