### ISSUE TITLE
When Installing Using Pip -- UnicodeDecodeError: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by joshglenn** [yashaka/selene#210]
When installing selene on python 3.8.2 64bit (Windows), this error occurs:

```
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Python\\src\\selene\\setup.py'"'"'; __file__='"'"'C:\\Python\\src\\selene\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: C:\Python\src\selene\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Python\src\selene\setup.py", line 6, in <module>
        long_description = open(join(abspath(dirname(__file__)), "README.md")).read()
      File "c:\python\python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 632: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

If I change line 6 as follows, the error goes away:

```
long_description = open(join(abspath(dirname(__file__)), "README.md" ), encoding="utf8").read()
```

**Comment by yashaka** [comment]
@joshglenn, thank you so much for the findings!
I have fixed it in 2.0.0a24, already released
Join our newly created telegram chat: https://t.me/selene_py
Let's grow the selene community there too;)
