### ISSUE TITLE
DelegatingMeta does not support bases without __abstractmethods__

### ISSUE THREAD

**Issue by vshevchenk** [yashaka/selene#230]
As TA I would like to use Generics in SeleneCollection inherited types so that I can have strongly typed Page Objects. Unfortunately `DelegatingMeta` has no support of generics as it requires `__abstractmethods__ `in base.

**Code to reproduce**
```
from typing import Generic, TypeVar

from selene.elements import SeleneCollection

T = TypeVar('T')


class MyCollection(SeleneCollection, Generic[T]):
    pass

```

**Output**
```
Traceback (most recent call last):
  File "/home/vshevchenk/PycharmProjects/.../tmp/tmp.py", line 8, in <module>
    class MyCollection(SeleneCollection, Generic[T]):
  File "/home/vshevchenk/PycharmProjects/.../venv/lib/python3.7/site-packages/selene/common/delegation.py", line 56, in __new__
    for base in bases))
  File "/home/vshevchenk/PycharmProjects/.../venv/lib/python3.7/site-packages/selene/common/delegation.py", line 56, in <genexpr>
    for base in bases))
AttributeError: __abstractmethods__
```

**Workaround**
```
from typing import Generic, TypeVar

from selene.common.delegation import _is_property, _make_delegator_method, _make_delegator_property, DelegatingMeta
from selene.elements import SeleneCollection

T = TypeVar('T')


def fixed_method(mcs, name, bases, dct):
    abstract_property_names = frozenset.union(
        *(frozenset(filter(lambda m: _is_property(m, base), base.__abstractmethods__))
          for base in bases if hasattr(base, '__abstractmethods__')))

    for base in bases:
        if hasattr(base, '__abstractmethods__'):
            base.__abstractmethods__ = frozenset(filter(lambda m: not _is_property(m, base), base.__abstractmethods__))

    abstract_method_names = frozenset.union(*(base.__abstractmethods__
                                              for base in bases if hasattr(base, '__abstractmethods__')))

    for name in abstract_method_names:
        if name not in dct:
            dct[name] = _make_delegator_method(name)

    # for name in abstract_property_names:
    #     if name not in dct:
    #         dct[name] = _make_delegator_method_to_property(name)

    cls = super(DelegatingMeta, mcs).__new__(mcs, name, bases, dct)

    for name in abstract_property_names:
        if name not in dct:
            setattr(cls, name, _make_delegator_property(name))

    return cls


def fix_delegating_meta():
    DelegatingMeta.__new__ = fixed_method


fix_delegating_meta()


class MyCollection(SeleneCollection, Generic[T]):
    pass

```

**Comment by yashaka** [comment]
Hey!

Seems like DelegatingMeta is not used anymore in Selene from 2.0x

Your question regards to selene 1.0, doesn't it?

Maybe you can just upgrade to 2.0 where the issue will not be relevant?

Correct me if I misunderstood something...

**Comment by vshevchenk** [comment]
@yashaka Thank you for the feedback. I did not consider to use 2.x.x. as it's in pre-release state but will give it a shot. I'll try to migrate a framework and post an update here

**Comment by yashaka** [comment]
Great! In case of any migration problem, do not hesitate to ask for help!

We also have chats in telegram where you can get help faster in most cases:

https://t.me/selene_py_ru
https://t.me/selene_py

**Comment by vshevchenk** [comment]
I acheved the goal by migrating to selene 2.x

**Comment by yashaka** [comment]
Great!
